/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-first_lora
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FIRST_LORA_API_H
#define INCLUDED_FIRST_LORA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_first_lora_EXPORTS
#define FIRST_LORA_API __GR_ATTR_EXPORT
#else
#define FIRST_LORA_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FIRST_LORA_API_H */
