/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(lora_detector.h) */
/* BINDTOOL_HEADER_FILE_HASH(d1fded58770aca79409611af6189ba60) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/first_lora/lora_detector.h>
// pydoc.h is automatically generated in the build directory
#include <lora_detector_pydoc.h>

void bind_lora_detector(py::module &m) {

  using lora_detector = ::gr::first_lora::lora_detector;

  py::class_<lora_detector, gr::block, gr::basic_block,
             std::shared_ptr<lora_detector>>(m, "lora_detector",
                                             D(lora_detector))

      .def(py::init(&lora_detector::make),
           py::arg("threshold") = 0.10000000000000001, py::arg("sf") = 7,
           py::arg("bw") = 125000, py::arg("method") = 0,
           D(lora_detector, make))

      ;
}
